### ISSUE TITLE
Works with the Nest?

### ISSUE THREAD

**Issue by Benjavalanche** [armzilla/amazon-echo-ha-bridge#46]
I saw a video online where someone used this to control their Nest as if it was a light bulb (brighness of 72 would be room temp).

I got the java app installed on my Rasperry Pi and running. I can get to the config portal on my PC, but now I am stuck. Does anyone have advice on how to set up the Nest as a device?

Thanks!

**Comment by madrigalo** [comment]
I was unsuccessful in having direct integration through the ha bridge. I was limited to turning the Nest on/off. I was more successful using IFTTT integration from the Echo to Nest.

**Comment by Benjavalanche** [comment]
How did you get the bridge to turn the Echo on and off? How do you set up
the IFTTT recipe?
Thanks in advance.

**Comment by jerrit** [comment]
You do not turn the echo off. You can setup ifttt with the maker channel and have urls trigger recipes.

**Comment by Benjavalanche** [comment]
I did not know I can do that. Can you share the recipe with me?

**Comment by jerrit** [comment]
Yep. So I do not have a Nest but my wemo light bulbs did not work native with the echo. This is just an example. https://ifttt.com/recipes/338520-maker-to-wemo-switch

**Comment by jerrit** [comment]
Let me know if have another question.

**Comment by ChrisWeiss** [comment]
FWIW - I dont think the Nest allows you to remotely set the temp outside
their applications (I would imagine for liability reasons). You can only
read information and set/un-set Away mode.

On Mon, Nov 2, 2015 at 11:13 AM, jerrit <notifications@github.com> wrote:

> Let me know if have another question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armzilla/amazon-echo-ha-bridge/issues/46#issuecomment-153128377>
> .
>



-- 
-Chris

**Comment by crashandburn45** [comment]
Using IFTTT you can create a recipe to set the Nest to a specific temperature. You won't have total control of the Nest but you can create recipes for common temperatures. Make sure you name the recipe something like "set the temperature to 72" so you can tell the echo to "ask Nest to set the temperature to 72"

**Comment by chapeter** [comment]
You can pass variables to IFTT maker channel as well, then pass those as temps to the nest channel.  I have that working for both a single temp for cool/heat, or a range when I'm in that mode

My setup for this looks something like:
Echo -> echo-ha-bridge -> OpenHab -> IFTTT -> Nest

Echo-ha-bridge sets a value in a dummy item in OpenHab.  OpenHab has a rule that when that value changes, posts the value to IFTT maker channel which feeds into the nest channel.

From: crashandburn45
Reply-To: armzilla/amazon-echo-ha-bridge
Date: Monday, November 2, 2015 at 1:56 PM
To: armzilla/amazon-echo-ha-bridge
Subject: Re: [amazon-echo-ha-bridge] Works with the Nest? (#46)


Using IFTTT you can create a recipe to set the Nest to a specific temperature. You won't have total control of the Nest but you can create recipes for common temperatures. Make sure you name the recipe something like "set the temperature to 72" so you can tell the echo to "ask Nest to set the temperature to 72"

**Comment by crashandburn45** [comment]
Even better. Thanks @chapeter .

**Comment by Benjavalanche** [comment]
how do you bet the echo to see the echo bridge once it is running?

**Comment by chapeter** [comment]
I loosely followed this guide:
http://tinsley.io/2015/06/control-your-items-using-the-amazon-echo-openhab/

I needed to open up UDP 1900 on my PI for the device discovery  to happen

**Comment by gpala7077** [comment]
@Benjavalanche 

Hey, I have successfully accomplished this. Although, I found that you have to regulate the temperature range. For example, if you want the temperature to be 75 degrees (Heat to)  and your upper range is 71 (Cool to) it wouldn't make sense since your lower limit has to be less than your upper limit. Thus, you have to regulate the range with Vera.  So this is a two part job.

In order to regulate it, I add this scene in Vera that runs every 2 seconds.  Use this code in the Luup Code Section:  (83 is my current device ID in vera), this code regulates the range to always be 5 degrees apart. 

==============================================================================
x = luup.variable_get("urn:upnp-org:serviceId:TemperatureSetpoint1_Heat","CurrentSetpoint",83)
y = luup.variable_get("urn:upnp-org:serviceId:TemperatureSetpoint1_Cool","CurrentSetpoint",83)

dif = y - x

if x > y then
luup.call_action("urn:upnp-org:serviceId:TemperatureSetpoint1_Cool","SetCurrentSetpoint",{NewCurrentSetpoint=x + 5},83)

elseif dif ~= 5 then

luup.call_action("urn:upnp-org:serviceId:TemperatureSetpoint1_Cool","SetCurrentSetpoint",{NewCurrentSetpoint=x + 5},83)

end
==============================================================================


In order to get it working with your Echo, using the config page on your Pi, add a new device call it: "The house temperature"  or anything you want just have to make it clear. 

For the "ON' section: Remember the Device 83 is MY device ID, you must replace that number with your device ID. 

Type this:  

http://YourIP:3480/data_request?id=action&output_format=json&DeviceNum=83&serviceId=urn:upnp-org:serviceId:TemperatureSetpoint1_Heat&action=SetCurrentSetpoint&NewCurrentSetpoint=${intensity.percent}

Save it.

After that, tell Alexa to discover devices, and now you should be good. Just know that it won't work by saying turn on the house temperature.  It will work by saying:  Set the House temperature to 75. And the nest will respond almost immediately.  

I use this at home and it works flawlessly!

**Comment by armzilla** [comment]
Native support exists
