### ISSUE TITLE
Getting harmony to use dim for volume

### ISSUE THREAD

**Issue by michaelhinchey** [armzilla/amazon-echo-ha-bridge#86]
I have an activity named voice and sound commands.  For ex. "Alexa, turn the sound on".. This toggles muting.  "Alexa turn the voice on" will turn the volume up on the receiver.  "Alexa, turn the voice off" will turn the volume down on the receiver.   I use voice for muting and unmuting and I use sound command for volume on my receiver.  My Question is how can I use the dim feature and adjust the volume percentage or number or whatever.  I would love to just say "Alexa, turn the voice to 0%" and it would mute.  Or "Alexa turn the volume to 50%".  OR even "Alexa, turn the volume down or up 10.  
Does anyone know how I can accomplish this?

**Comment by digiltd** [comment]
I have also been playing with this. It depends on the type of amp, do you have one that lets you input a level numerically using something like [vol][4][0][send]? or do you have to press and hold the volume up/down button and wait till you get to the level you want?

I had limited success using openHAB and then sending percentages to dummy items for volUp and volDown. When the percentage is received it sends out button presses to the amp and repeats based on the number divided by 3 (because 80 presses is a lot of presses :) )

You have to have two devices (**amp sound up** and **amp sound down**) and call them using "Alexa, set amp sound up 50%" or "Alexa, set amp sound down 30%" 

It works, but in practice it is pretty crappy. For something like volume you need a bit of precision and shouting at the echo constantly is not very precise :)

**Comment by michaelhinchey** [comment]
I have a receiver/amp that you have to press the button to raise or lower volume.  I would be happy with what you have achieved for now.  How did you set it up?

**Comment by digiltd** [comment]
Do you already use openHAB? If not then it really isn't worth setting it up just for this as whilst it "works" it really isn't usable.

**Comment by michaelhinchey** [comment]
No I don't use openhab.  I haven't really looked into it either.  Should I
for home automation?







         Every dream is a goal with a date on it; if you can conceive it
believe it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by digiltd** [comment]
Trouble is to do it the way I described you need something to take the percentage you set and turn it into "button presses" and then send the commands to the hub. But setting up openHAB is not that simple, and I can't easily give instructions on how to do it. So I think at this stage the answer to your original question is "not yet".

**Comment by michaelhinchey** [comment]
OK.  I won't get into openhab yet.  I'm wondering how to get the button
presses?
   Will habridge actually do this?  Do you know?  I'm wondering if I can
make a harmony button say named "amp ten".  Can I actually have it On url
[{"device"."38800201","button"."VolumeUp"}]
Can I do something in between the [{   }] to multiply the action?







         Every dream is a goal with a date on it; if you can conceive it
believe it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by Juppers** [comment]
I would love to see the ability to activate a button x times like this.

**Comment by bwssytems** [comment]
Since you are using a different bridge than this git page, you may want to look for the answers there.... 
https://github.com/bwssytems/ha-bridge
